version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: chessgames
      POSTGRES_USER: # <-- FILL IN YOUR USERNAME
      POSTGRES_PASSWORD: # <-- FILL IN YOUR PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chessgames
      SPRING_DATASOURCE_USERNAME: # <-- FILL IN YOUR USERNAME
      SPRING_DATASOURCE_PASSWORD: # <-- FILL IN YOUR PASSWORD
    ports:
      - "8080:8080"

  python-scheduler:
    build:
      context: ./scripts/Chess-Analysing-Pi
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: # <-- FILL IN YOUR USERNAME
      DB_PASSWORD: # <-- FILL IN YOUR PASSWORD
      DB_NAME: chessgames
      CHESS_USERNAME: # <-- FILL IN YOUR CHESS.COM USERNAME
      ENV_Test: prod
    entrypoint: ["sh", "-c", "while true; do python3 ChessDB_updating_service.py std; sleep 86400; done"]

volumes:
  db-data:
